In [5]:
import pandas as pd

df_vehicle_crashes = pd.read_parquet("../vehicle_crashes_cleaned.parquet")
df_vehicle_crashes_vehicle = pd.read_parquet("../vehicle_crashes_vehicle_cleaned.parquet")
df_vehicle_crashes_person = pd.read_parquet("../vehicle_crashes_person_cleaned.parquet")

FileNotFoundError: [Errno 2] No such file or directory: '../vehicle_crashes_cleaned.parquet'

In [2]:
df_vehicle_crashes.head(5)

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,ON STREET NAME,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,...,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3
0,2021-09-11,2:39,NaN,NaN,NaN,NaN,WHITESTONE EXPRESSWAY,2.0,0.0,0,...,0,2,0,Aggressive Driving/Road Rage,Unspecified,NaN,4455765,Sedan,Sedan,NaN
1,2022-03-26,11:45,NaN,NaN,NaN,NaN,QUEENSBORO BRIDGE UPPER,1.0,0.0,0,...,0,1,0,Pavement Slippery,NaN,NaN,4513547,Sedan,NaN,NaN
2,2023-11-01,1:29,BROOKLYN,11230.0,40.62179,-73.970024,OCEAN PARKWAY,1.0,0.0,0,...,0,1,0,Unspecified,Unspecified,Unspecified,4675373,Moped,Sedan,Sedan
3,2022-06-29,6:55,NaN,NaN,NaN,NaN,THROGS NECK BRIDGE,0.0,0.0,0,...,0,0,0,Following Too Closely,Unspecified,NaN,4541903,Sedan,Pick-up Truck,NaN
4,2022-09-21,13:21,NaN,NaN,NaN,NaN,BROOKLYN BRIDGE,0.0,0.0,0,...,0,0,0,Passing Too Closely,Unspecified,NaN,4566131,Station Wagon/Sport Utility Vehicle,NaN,NaN

In [3]:
df_vehicle_crashes_vehicle.head(5)

,COLLISION_ID,CRASH_DATE,CRASH_TIME,VEHICLE_TYPE,VEHICLE_MAKE,VEHICLE_MODEL,VEHICLE_YEAR,TRAVEL_DIRECTION,VEHICLE_OCCUPANTS,DRIVER_SEX,DRIVER_LICENSE_STATUS,PRE_CRASH,POINT_OF_IMPACT,VEHICLE_DAMAGE,PUBLIC_PROPERTY_DAMAGE,CONTRIBUTING_FACTOR_1,CONTRIBUTING_FACTOR_2
0,100201,09/07/2012,9:03,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unspecified,NaN
1,4213082,09/23/2019,8:15,Station Wagon/Sport Utility Vehicle,TOYT -CAR/SUV,NaN,2002.0,North,1.0,M,Licensed,Going Straight Ahead,Left Front Bumper,Left Front Quarter Panel,N,Driver Inattention/Distraction,Unspecified
2,3307608,10/02/2015,17:18,TAXI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Going Straight Ahead,NaN,NaN,NaN,Driver Inattention/Distraction,NaN
3,3308693,10/04/2015,20:34,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parked,NaN,NaN,NaN,Unspecified,NaN
4,297666,04/25/2013,21:15,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other Vehicular,NaN

In [4]:
df_vehicle_crashes_person.head(5)

,COLLISION_ID,CRASH_DATE,CRASH_TIME,PERSON_TYPE,PERSON_INJURY,PERSON_AGE,EJECTION,POSITION_IN_VEHICLE,SAFETY_EQUIPMENT,PED_LOCATION,PED_ACTION,CONTRIBUTING_FACTOR_1,CONTRIBUTING_FACTOR_2,PERSON_SEX
0,4229554,10/26/2019,9:43,Occupant,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U
1,4230587,10/25/2019,15:15,Occupant,Unspecified,33.0,Not Ejected,"Front passenger, if two or more persons, inclu...",Lap Belt & Harness,NaN,NaN,NaN,NaN,F
2,4230550,10/26/2019,17:55,Occupant,Unspecified,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M
3,3565527,11/21/2016,13:05,Occupant,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4231168,10/25/2019,11:16,Occupant,Unspecified,7.0,Not Ejected,Right rear passenger or motorcycle sidecar pas...,Lap Belt,NaN,NaN,NaN,NaN,F